### ISSUE TITLE
Doesn't work on index pages in Jekyll 2.5.3

### ISSUE THREAD

**Issue by microcosm** [xHN35RQ/jekyll-ideal-image-slider#1]
Hi,

This works fine on landing pages (full blog posts) but does not render the relevant script tags on index pages.

This renders scripts:
```
<!-- Sliders on pages -->
{% for script in page.slider_scripts %}
  {{ script }}
{% endfor %}
```
This doesn't:
```
<!-- Sliders on indexes -->
{% for post in paginator.posts %}
  {% for script in post.slider_scripts %}
    {{ script }}
  {% endfor %}
{% endfor %}
```

The `paginator.posts` collection has entries on my index pages. However the `slider_scripts` collection is empty on index pages.

**Comment by xHN35RQ** [comment]
Odd. I have it working well in production.

Did you add the empty array `slider_array: []` to your config.yml? I am using a [hacky method](https://github.com/xHN35RQ/jekyll-ideal-image-slider/blob/master/ideal_image_slider.rb#L73-75) to create the `slider_scripts` collection that requires the empty array `slider_array` to be present before the plugin runs. I didn't know of a way to create a persistent array from within the plugin itself.

By the way if you know of a better method to create this persistent array that doesn't require adding an empty array to the config.yml I'd be interested to know.

**Comment by xHN35RQ** [comment]
By the way, which version of Jekyll are you using? 

This is the code block we're using in production right now. This is from `default.html` layout:

```
  {% if page.slider_active or page.index %}
    <!-- Slider -->
    <script src="{{ site.baseurl }}/assets/js/slider.js"></script>
    <!-- Slider Creation on pages -->
    {% for script in page.slider_scripts %}
      {{ script }}
    {% endfor %}
    <!-- Slider Creation on indexes -->
    {% for post in paginator.posts %}
      {% for script in post.slider_scripts %}
        {{ script }}
      {% endfor %}
    {% endfor %}
  {% endif %}
```

**Comment by xHN35RQ** [comment]
@microcosm I cloned your site, and tested against your code, and sliders are working fine for me in individual posts as well as in the index of /blog/ - was it another index you noticed a problem with?

I tested the newest post (/home/nick/Projects/art-a-hack.github.io/app/_posts/2016-06-25-photos-from-week-3-2016.markdown) and dropped the following code into it, and your site displayed a slider in the post as well as the blog index.

```
{% slider %}
  ![alt text 1](/images/blog/2016/kinect-vr1.jpg)
  ![alt text 2](/images/blog/2016/kinect-vr2.jpg)
  ![alt text 3](/images/blog/2016/kinect-vr3.jpg)
{% endslider %}
```

**Comment by xHN35RQ** [comment]
On further investigation, in Jekyll 2.5.3 `post.slider_scripts` is empty after being retrieved using `paginator.posts` but in Jekyll 3 it contains the slider scripts for that page. Perhaps there's another way of accessing `post.slider_scripts` that is 2.5.3-friendly? The other option is to upgrade to Jekyll 3.

**Comment by xHN35RQ** [comment]
Further investigation is needed, if someone else reports this doesn't work on 2.5.3 I'll re-open and go from there.

**Comment by microcosm** [comment]
Hi, thanks for looking into that. I have now updated all dependencies, I am now on Jekyll 3.1.6. However, now it doesn't work on either index page or post page.

**Comment by microcosm** [comment]
The repo: https://github.com/Art-A-Hack/art-a-hack.github.io

**Comment by microcosm** [comment]
Note that in the public version of the repo I have used a hack just to get it working while we figure it out:

```
    {% for script in site.slider_array %}
      {{ script }}
    {% endfor %}
```

Of course that won't scale well. 

Locally I am trying to use the [instructions here](https://github.com/xHN35RQ/jekyll-ideal-image-slider), but it doesn't work.

**Comment by xHN35RQ** [comment]
Thanks for the updates. I'm also using Jekyll 3.1.6 and this plugin in production. So far all works well. I'll investigate and try to determine why this is acting differently on your site.

**Comment by xHN35RQ** [comment]
Thanks for the updates. I'm also using Jekyll 3.1.6 and this plugin in production. So far all works well. I'll investigate and try to determine why this is acting differently on your site. It may be (probably is) a fault of my very rudimentary knowledge of Ruby/Jekyll.

**Comment by xHN35RQ** [comment]
@microcosm after investigation I can confirm it's working for me using in single blog posts, and blog indexes using this commit: https://github.com/xHN35RQ/art-a-hack.github.io/commit/acb4c75f0786a93326198f4af6a1d7df9e6e754f

By the way, `grunt buidl

**Comment by xHN35RQ** [comment]
@microcosm after investigation I can confirm it's working for me using in single blog posts, and blog indexes using this commit: xHN35RQ/art-a-hack.github.io@acb4c75

By the way, `grunt build` fails because `scss-lint` has been renamed to `scss_lint` so that may need to be updated in the Gemfile.

**Comment by microcosm** [comment]
I just re-tried it using your fork as a guide. It works! I must have been doing something wrong last time. Thanks so much for taking the time to investigate.

**Comment by xHN35RQ** [comment]
Cool, glad it's working now! I'm still not sure if this plugin works on Jekyll 2.5.3 or not so I've retitled this issue and we'll see if anyone can confirm.
