### ISSUE TITLE
Page build failure, tag 'slider'  is not a recognized Liquid tag

### ISSUE THREAD

**Issue by bonobo** [xHN35RQ/jekyll-ideal-image-slider#2]
Hi, I used your plugin on my website and if I build my site locally with jekyll everything works perfectly. But when I upload it to github, it doesn't work due build failure.

Have you ever this kind of problem.

Thanks for your help.

**Comment by xHN35RQ** [comment]
Yes, Github Pages does not allow custom plugins. They only allow the plugins found in the Github Pages gem. More info here:

https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/

If you want to use this plugin slider on Github Pages, you'll need to build the site locally, and push the built files up to Github Pages.

**Comment by xHN35RQ** [comment]
I see you have your repository in `master`. You might consider creating a new branch `gh-pages` and building your Jekyll site locally, commiting it to this branch, and push the `gh-pages` branch. Then set your repository to host from `gh-pages`.

**Comment by xHN35RQ** [comment]
closing

**Comment by jekylltools** [comment]
You can use https://github.com/jekylltools/jekyll-ideal-image-slider-include to add image sliders on Github Pages.
